# Spring properties
spring:
  application:
    name: auth-service

# Mongo properties
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local


# HTTP Server
server:
  port: 8888
  
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION

# Auth JWT
jwt:
  header: Authorization
  secret: quebic_secret
  expiration: 172800 #seconds
  route:
    authentication:
      path: auth
      refresh: refresh

# Image Upload Location
image:
  upload:
    location: /Users/srkapi/Documents/intellij/example-micro
    
# Email
email:
  userName: albertowas12@hotmail.com
  password: Alberto699734040
