# Spring properties
spring:
  application:
    name: order-service

# Mongo properties
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local


# HTTP Server
server:
  port: 5465

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION

# Auth JWT
jwt:
  header: Authorization
  secret: quebic_secret
  expiration: 172800 #seconds
  route:
    authentication:
      path: auth
      refresh: refresh
